---
- name: Gather OS system specific variables
  ansible.builtin.include_vars: "{{ ansible_system }}.yml"

- name: Gather Distribution specific variables
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_system }}-{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_system }}-{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_system }}-{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
        - "{{ ansible_system }}-{{ ansible_os_family }}.yml"
        - "default.yml"
      paths:
        - vars

- name: Configure system users
  ansible.builtin.include_tasks: users.yml

- name: Install default packages
  ansible.builtin.include_tasks: packages.yml

- name: Configure system
  ansible.builtin.include_tasks: configure.yml

- name: Configure time sync
  ansible.builtin.include_tasks: ntp.yml
